services:
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    volumes:
      - ./api:/app
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - elasticsearch
      - optimizer

  postgres:
    image: postgres:18.4
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - 5432:5432
    attach: false
    volumes:
      - postgres_data:/var/lib/postgresql

  elasticsearch:
    image: elasticsearch:9.5.2
    container_name: elasticsearch
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    ports:
      - 9200:9200
    attach: false
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  optimizer:
    build:
      dockerfile: Dockerfile.dev
      context: ./optimizer
    ports:
      - 50051:50051
    develop:
      watch:
        - action: sync+restart
          path: ./optimizer/src
          target: /app/src
        - action: rebuild
          path: ./optimizer/pyproject.toml

volumes:
  postgres_data:
  elasticsearch_data: