FROM golang:1.26-alpine
WORKDIR /app

RUN go install github.com/pressly/goose/v3/cmd/goose@v3.27.3

COPY internal/database/migrations ./migrations

ENV GOOSE_MIGRATION_DIR=./migrations

ENTRYPOINT ["goose", "up"]