// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: buildings.sql

package sqlc

import (
	"context"
)

const listBuildings = `-- name: ListBuildings :many
SELECT
    id,
    name,
    code,
    latitude,
    longitude
FROM buildings
ORDER BY name ASC
`

func (q *Queries) ListBuildings(ctx context.Context) ([]Building, error) {
	rows, err := q.db.Query(ctx, listBuildings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Building{}
	for rows.Next() {
		var i Building
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Latitude,
			&i.Longitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
