// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: classes.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listClassesByID = `-- name: ListClassesByID :many
SELECT
    cl.id,
    cl.number,
    cl.note,
    cl.meet_type,

    COALESCE(
        (
            SELECT jsonb_agg(
                jsonb_build_object(
                    'days', cmt.days,
                    'time_start', cmt.time_begin,
                    'time_end', cmt.time_end,
                    'period_start', cmt.period_begin,
                    'period_end', cmt.period_end,
                    'building',
                    CASE
                        WHEN b.id IS NULL THEN NULL
                        ELSE jsonb_build_object(
                            'name', b.name,
                            'code', b.code,
                            'room', NULLIF(cmt.room, '')
                        )
                    END
                )
            )
            FROM class_meet_times cmt
            LEFT JOIN buildings b
                ON b.id = cmt.building_id
            WHERE cmt.class_id = cl.id
        ),
        '[]'::jsonb
    ) AS meet_times,

    COALESCE(
        (
            SELECT jsonb_agg(
                jsonb_build_object(
                    'name', i.name,
                    'rmp_id', i.rmp_id,
                    'rating', i.rating,
                    'difficulty', i.difficulty,
                    'take_again', i.take_again
                )
            )
            FROM class_instructors ci
            JOIN instructors i
                ON i.id = ci.instructor_id
            WHERE ci.class_id = cl.id
        ),
        '[]'::jsonb
    ) AS instructors

FROM unnest($1::uuid[]) WITH ORDINALITY AS ids(id, ord)
JOIN classes cl
    ON cl.id = ids.id
ORDER BY ids.ord
`

type ListClassesByIDRow struct {
	ID          uuid.UUID     `json:"id"`
	Number      int32         `json:"number"`
	Note        *string       `json:"note"`
	MeetType    ClassMeetType `json:"meet_type"`
	MeetTimes   interface{}   `json:"meet_times"`
	Instructors interface{}   `json:"instructors"`
}

func (q *Queries) ListClassesByID(ctx context.Context, ids []uuid.UUID) ([]ListClassesByIDRow, error) {
	rows, err := q.db.Query(ctx, listClassesByID, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClassesByIDRow{}
	for rows.Next() {
		var i ListClassesByIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Note,
			&i.MeetType,
			&i.MeetTimes,
			&i.Instructors,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClassesForScheduler = `-- name: ListClassesForScheduler :many
SELECT
    cl.course_id,
    cl.id AS class_id,
    cmt.days,
    cmt.time_begin,
    cmt.time_end
FROM unnest($1::uuid[]) WITH ORDINALITY AS ids(id, ord)
JOIN classes cl
    ON cl.id = ids.id
LEFT JOIN class_meet_times cmt
    ON cmt.class_id = cl.id
WHERE cl.term_id = $2
ORDER BY ids.ord
`

type ListClassesForSchedulerParams struct {
	ClassIds []uuid.UUID `json:"class_ids"`
	TermID   int32       `json:"term_id"`
}

type ListClassesForSchedulerRow struct {
	CourseID  uuid.UUID     `json:"course_id"`
	ClassID   uuid.UUID     `json:"class_id"`
	Days      []MeetDayType `json:"days"`
	TimeBegin pgtype.Time   `json:"time_begin"`
	TimeEnd   pgtype.Time   `json:"time_end"`
}

func (q *Queries) ListClassesForScheduler(ctx context.Context, arg ListClassesForSchedulerParams) ([]ListClassesForSchedulerRow, error) {
	rows, err := q.db.Query(ctx, listClassesForScheduler, arg.ClassIds, arg.TermID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClassesForSchedulerRow{}
	for rows.Next() {
		var i ListClassesForSchedulerRow
		if err := rows.Scan(
			&i.CourseID,
			&i.ClassID,
			&i.Days,
			&i.TimeBegin,
			&i.TimeEnd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const validateClassesForTerm = `-- name: ValidateClassesForTerm :many
SELECT cl.id
FROM unnest($1::uuid[]) AS ids(id)
JOIN classes cl
    ON cl.id = ids.id
WHERE cl.term_id = $2
`

type ValidateClassesForTermParams struct {
	ClassIds []uuid.UUID `json:"class_ids"`
	TermID   int32       `json:"term_id"`
}

func (q *Queries) ValidateClassesForTerm(ctx context.Context, arg ValidateClassesForTermParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, validateClassesForTerm, arg.ClassIds, arg.TermID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
