// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: classes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const searchClasses = `-- name: SearchClasses :many
SELECT
    cl.id,
    cl.number,
    cl.note,
    cl.meet_type,

    c.is_lab AS course_is_lab,
    c.name AS course_name,
    c.description AS course_description,
    c.prerequisites AS course_prerequisites,

    jsonb_build_object(
        'gte', c.credits_min,
        'lte', c.credits_max
    ) AS course_credits,

    d.name AS course_department,
    c.words AS course_words,
    to_jsonb(c.gen_eds) AS course_gen_eds,
    c.quest AS course_quest,
    c.is_ai AS course_is_ai,
    c.is_honors AS course_is_honors,

    COALESCE(
        (
            SELECT jsonb_agg(
                jsonb_build_object(
                    'days', cmt.days,

                    'time_start',
                        EXTRACT(HOUR FROM cmt.time_begin)::integer * 60
                        + EXTRACT(MINUTE FROM cmt.time_begin)::integer,
                    'time_end',
                        EXTRACT(HOUR FROM cmt.time_end)::integer * 60
                        + EXTRACT(MINUTE FROM cmt.time_end)::integer,

                    'period_start',
                    CASE
                        WHEN cmt.period_begin LIKE 'E%%'
                            THEN 11 + substring(
                                cmt.period_begin FROM 2
                            )::integer
                        ELSE NULLIF(cmt.period_begin, '')::integer
                    END,
                    'period_end',
                    CASE
                        WHEN cmt.period_end LIKE 'E%%'
                            THEN 11 + substring(
                                cmt.period_end FROM 2
                            )::integer
                        ELSE NULLIF(cmt.period_end, '')::integer
                    END,

                    'building', cmt.building
                )
            )
            FROM class_meet_times cmt
            WHERE cmt.class_id = cl.id
        ),
        '[]'::jsonb
    ) AS meet_times,

    COALESCE(
        (
            SELECT jsonb_agg(
                jsonb_build_object(
                    'name', i.name,
                    'rating', i.rating,
                    'difficulty', i.difficulty,
                    'take_again', i.take_again
                )
            )
            FROM class_instructors ci
            JOIN instructors i
                ON i.id = ci.instructor_id
            WHERE ci.class_id = cl.id
        ),
        '[]'::jsonb
    ) AS instructors

FROM classes cl

JOIN courses c
    ON c.id = cl.course_id
    AND c.term_id = cl.term_id

JOIN departments d
    ON d.id = c.department_id
`

type SearchClassesRow struct {
	ID                  pgtype.UUID   `json:"id"`
	Number              int32         `json:"number"`
	Note                *string       `json:"note"`
	MeetType            ClassMeetType `json:"meet_type"`
	CourseIsLab         *bool         `json:"course_is_lab"`
	CourseName          string        `json:"course_name"`
	CourseDescription   string        `json:"course_description"`
	CoursePrerequisites string        `json:"course_prerequisites"`
	CourseCredits       []byte        `json:"course_credits"`
	CourseDepartment    string        `json:"course_department"`
	CourseWords         int32         `json:"course_words"`
	CourseGenEds        []byte        `json:"course_gen_eds"`
	CourseQuest         NullQuest     `json:"course_quest"`
	CourseIsAi          bool          `json:"course_is_ai"`
	CourseIsHonors      bool          `json:"course_is_honors"`
	MeetTimes           interface{}   `json:"meet_times"`
	Instructors         interface{}   `json:"instructors"`
}

func (q *Queries) SearchClasses(ctx context.Context) ([]SearchClassesRow, error) {
	rows, err := q.db.Query(ctx, searchClasses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchClassesRow{}
	for rows.Next() {
		var i SearchClassesRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Note,
			&i.MeetType,
			&i.CourseIsLab,
			&i.CourseName,
			&i.CourseDescription,
			&i.CoursePrerequisites,
			&i.CourseCredits,
			&i.CourseDepartment,
			&i.CourseWords,
			&i.CourseGenEds,
			&i.CourseQuest,
			&i.CourseIsAi,
			&i.CourseIsHonors,
			&i.MeetTimes,
			&i.Instructors,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
