// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: classes.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const listClassesByID = `-- name: ListClassesByID :many
SELECT
    cl.number,
    cl.note,
    cl.meet_type,

    COALESCE(
        (
            SELECT jsonb_agg(
                jsonb_build_object(
                    'days', cmt.days,
                    'time_start', cmt.time_begin,
                    'time_end', cmt.time_end,
                    'period_start', cmt.period_begin,
                    'period_end', cmt.period_end,
                    'building',
                    CASE
                        WHEN cmt.room IS NOT NULL
                            AND cmt.room <> ''
                        THEN b.name || ' ' || cmt.room
                        ELSE b.code
                    END
                )
            )
            FROM class_meet_times cmt
            LEFT JOIN buildings b
                ON b.id = cmt.building_id
            WHERE cmt.class_id = cl.id
        ),
        '[]'::jsonb
    ) AS meet_times,

    COALESCE(
        (
            SELECT jsonb_agg(
                jsonb_build_object(
                    'name', i.name,
                    'rmp_id', i.rmp_id,
                    'rating', i.rating,
                    'difficulty', i.difficulty,
                    'take_again', i.take_again
                )
            )
            FROM class_instructors ci
            JOIN instructors i
                ON i.id = ci.instructor_id
            WHERE ci.class_id = cl.id
        ),
        '[]'::jsonb
    ) AS instructors

FROM unnest($1::uuid[]) WITH ORDINALITY AS ids(id, ord)
JOIN classes cl
    ON cl.id = ids.id
ORDER BY ids.ord
`

type ListClassesByIDRow struct {
	Number      int32         `json:"number"`
	Note        *string       `json:"note"`
	MeetType    ClassMeetType `json:"meet_type"`
	MeetTimes   interface{}   `json:"meet_times"`
	Instructors interface{}   `json:"instructors"`
}

func (q *Queries) ListClassesByID(ctx context.Context, ids []uuid.UUID) ([]ListClassesByIDRow, error) {
	rows, err := q.db.Query(ctx, listClassesByID, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClassesByIDRow{}
	for rows.Next() {
		var i ListClassesByIDRow
		if err := rows.Scan(
			&i.Number,
			&i.Note,
			&i.MeetType,
			&i.MeetTimes,
			&i.Instructors,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
