// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: courses.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listCoursesByID = `-- name: ListCoursesByID :many
SELECT
    c.code,
    c.is_lab,
    c.name,
    c.description,
    c.syllabus,
    c.prerequisites,
    c.credits_min,
    c.credits_max,
    c.words,
    to_jsonb(c.gen_eds) AS gen_eds,
    c.quest,
    c.is_ai,
    c.is_honors,

    d.name AS department

FROM unnest($1::integer[]) WITH ORDINALITY AS ids(id, ord)
JOIN courses c
    ON c.id = ids.id
JOIN departments d
    ON d.id = c.department_id
ORDER BY ids.ord
`

type ListCoursesByIDRow struct {
	Code          string         `json:"code"`
	IsLab         *bool          `json:"is_lab"`
	Name          string         `json:"name"`
	Description   string         `json:"description"`
	Syllabus      string         `json:"syllabus"`
	Prerequisites string         `json:"prerequisites"`
	CreditsMin    pgtype.Numeric `json:"credits_min"`
	CreditsMax    pgtype.Numeric `json:"credits_max"`
	Words         int32          `json:"words"`
	GenEds        []byte         `json:"gen_eds"`
	Quest         NullQuest      `json:"quest"`
	IsAi          bool           `json:"is_ai"`
	IsHonors      bool           `json:"is_honors"`
	Department    string         `json:"department"`
}

func (q *Queries) ListCoursesByID(ctx context.Context, ids []int32) ([]ListCoursesByIDRow, error) {
	rows, err := q.db.Query(ctx, listCoursesByID, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCoursesByIDRow{}
	for rows.Next() {
		var i ListCoursesByIDRow
		if err := rows.Scan(
			&i.Code,
			&i.IsLab,
			&i.Name,
			&i.Description,
			&i.Syllabus,
			&i.Prerequisites,
			&i.CreditsMin,
			&i.CreditsMax,
			&i.Words,
			&i.GenEds,
			&i.Quest,
			&i.IsAi,
			&i.IsHonors,
			&i.Department,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
