// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: departments.sql

package sqlc

import (
	"context"
)

const listDepartments = `-- name: ListDepartments :many
SELECT DISTINCT name FROM departments ORDER BY name ASC
`

func (q *Queries) ListDepartments(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listDepartments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
