// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ClassMeetType string

const (
	ClassMeetTypePrimarilyClassroom ClassMeetType = "Primarily Classroom"
	ClassMeetTypeHybrid             ClassMeetType = "Hybrid"
	ClassMeetTypeOnline8099         ClassMeetType = "Online (80-99%)"
	ClassMeetTypeOnline100          ClassMeetType = "Online (100%)"
)

func (e *ClassMeetType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ClassMeetType(s)
	case string:
		*e = ClassMeetType(s)
	default:
		return fmt.Errorf("unsupported scan type for ClassMeetType: %T", src)
	}
	return nil
}

type NullClassMeetType struct {
	ClassMeetType ClassMeetType `json:"class_meet_type"`
	Valid         bool          `json:"valid"` // Valid is true if ClassMeetType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullClassMeetType) Scan(value interface{}) error {
	if value == nil {
		ns.ClassMeetType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ClassMeetType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullClassMeetType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ClassMeetType), nil
}

type CourseCreditsType string

const (
	CourseCreditsTypeFIXED    CourseCreditsType = "FIXED"
	CourseCreditsTypeVARIABLE CourseCreditsType = "VARIABLE"
)

func (e *CourseCreditsType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CourseCreditsType(s)
	case string:
		*e = CourseCreditsType(s)
	default:
		return fmt.Errorf("unsupported scan type for CourseCreditsType: %T", src)
	}
	return nil
}

type NullCourseCreditsType struct {
	CourseCreditsType CourseCreditsType `json:"course_credits_type"`
	Valid             bool              `json:"valid"` // Valid is true if CourseCreditsType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCourseCreditsType) Scan(value interface{}) error {
	if value == nil {
		ns.CourseCreditsType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CourseCreditsType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCourseCreditsType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CourseCreditsType), nil
}

type GenEd string

const (
	GenEdBiologicalScience GenEd = "Biological Science"
	GenEdPhysicalScience   GenEd = "Physical Science"
	GenEdSocialScience     GenEd = "Social Science"
	GenEdMathematics       GenEd = "Mathematics"
	GenEdComposition       GenEd = "Composition"
	GenEdHumanities        GenEd = "Humanities"
	GenEdInternational     GenEd = "International"
)

func (e *GenEd) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GenEd(s)
	case string:
		*e = GenEd(s)
	default:
		return fmt.Errorf("unsupported scan type for GenEd: %T", src)
	}
	return nil
}

type NullGenEd struct {
	GenEd GenEd `json:"gen_ed"`
	Valid bool  `json:"valid"` // Valid is true if GenEd is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGenEd) Scan(value interface{}) error {
	if value == nil {
		ns.GenEd, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GenEd.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGenEd) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GenEd), nil
}

type MeetDayType string

const (
	MeetDayTypeM MeetDayType = "M"
	MeetDayTypeT MeetDayType = "T"
	MeetDayTypeW MeetDayType = "W"
	MeetDayTypeR MeetDayType = "R"
	MeetDayTypeF MeetDayType = "F"
	MeetDayTypeS MeetDayType = "S"
	MeetDayTypeU MeetDayType = "U"
)

func (e *MeetDayType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MeetDayType(s)
	case string:
		*e = MeetDayType(s)
	default:
		return fmt.Errorf("unsupported scan type for MeetDayType: %T", src)
	}
	return nil
}

type NullMeetDayType struct {
	MeetDayType MeetDayType `json:"meet_day_type"`
	Valid       bool        `json:"valid"` // Valid is true if MeetDayType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMeetDayType) Scan(value interface{}) error {
	if value == nil {
		ns.MeetDayType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MeetDayType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMeetDayType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MeetDayType), nil
}

type Period string

const (
	Period1  Period = "1"
	Period2  Period = "2"
	Period3  Period = "3"
	Period4  Period = "4"
	Period5  Period = "5"
	Period6  Period = "6"
	Period7  Period = "7"
	Period8  Period = "8"
	Period9  Period = "9"
	Period10 Period = "10"
	Period11 Period = "11"
	PeriodE1 Period = "E1"
	PeriodE2 Period = "E2"
	PeriodE3 Period = "E3"
)

func (e *Period) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Period(s)
	case string:
		*e = Period(s)
	default:
		return fmt.Errorf("unsupported scan type for Period: %T", src)
	}
	return nil
}

type NullPeriod struct {
	Period Period `json:"period"`
	Valid  bool   `json:"valid"` // Valid is true if Period is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPeriod) Scan(value interface{}) error {
	if value == nil {
		ns.Period, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Period.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPeriod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Period), nil
}

type Quest string

const (
	QuestQuest1 Quest = "Quest 1"
	QuestQuest2 Quest = "Quest 2"
	QuestQuest3 Quest = "Quest 3"
	QuestQuest4 Quest = "Quest 4"
)

func (e *Quest) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Quest(s)
	case string:
		*e = Quest(s)
	default:
		return fmt.Errorf("unsupported scan type for Quest: %T", src)
	}
	return nil
}

type NullQuest struct {
	Quest Quest `json:"quest"`
	Valid bool  `json:"valid"` // Valid is true if Quest is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullQuest) Scan(value interface{}) error {
	if value == nil {
		ns.Quest, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Quest.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullQuest) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Quest), nil
}

type Building struct {
	ID        uuid.UUID      `json:"id"`
	Name      string         `json:"name"`
	Code      string         `json:"code"`
	Latitude  pgtype.Numeric `json:"latitude"`
	Longitude pgtype.Numeric `json:"longitude"`
}

type Class struct {
	ID             uuid.UUID     `json:"id"`
	TermID         int32         `json:"term_id"`
	Number         int32         `json:"number"`
	Note           *string       `json:"note"`
	MeetType       ClassMeetType `json:"meet_type"`
	IngestionRunID pgtype.UUID   `json:"ingestion_run_id"`
	CourseID       uuid.UUID     `json:"course_id"`
}

type ClassInstructor struct {
	ClassID      uuid.UUID `json:"class_id"`
	InstructorID uuid.UUID `json:"instructor_id"`
}

type ClassMeetTime struct {
	ID          uuid.UUID     `json:"id"`
	ClassID     uuid.UUID     `json:"class_id"`
	Number      int32         `json:"number"`
	Days        []MeetDayType `json:"days"`
	TimeBegin   pgtype.Time   `json:"time_begin"`
	TimeEnd     pgtype.Time   `json:"time_end"`
	PeriodBegin Period        `json:"period_begin"`
	PeriodEnd   Period        `json:"period_end"`
	BuildingID  pgtype.UUID   `json:"building_id"`
	Room        *string       `json:"room"`
}

type Course struct {
	UfID           int32                 `json:"uf_id"`
	TermID         int32                 `json:"term_id"`
	Code           string                `json:"code"`
	CodePrefix     string                `json:"code_prefix"`
	IsLab          bool                  `json:"is_lab"`
	Name           string                `json:"name"`
	Description    string                `json:"description"`
	Syllabus       string                `json:"syllabus"`
	Prerequisites  string                `json:"prerequisites"`
	CreditsMin     pgtype.Numeric        `json:"credits_min"`
	CreditsMax     pgtype.Numeric        `json:"credits_max"`
	DepartmentID   uuid.UUID             `json:"department_id"`
	Words          int32                 `json:"words"`
	GenEds         []GenEd               `json:"gen_eds"`
	Quest          NullQuest             `json:"quest"`
	IsAi           bool                  `json:"is_ai"`
	IsHonors       bool                  `json:"is_honors"`
	IngestionRunID pgtype.UUID           `json:"ingestion_run_id"`
	CreditsType    NullCourseCreditsType `json:"credits_type"`
	Level          int32                 `json:"level"`
	ID             uuid.UUID             `json:"id"`
}

type Department struct {
	ID   uuid.UUID `json:"id"`
	Code int32     `json:"code"`
	Name string    `json:"name"`
}

type IngestionRun struct {
	ID        uuid.UUID          `json:"id"`
	TermID    int32              `json:"term_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Instructor struct {
	ID         uuid.UUID          `json:"id"`
	Name       string             `json:"name"`
	RmpID      *int32             `json:"rmp_id"`
	Rating     pgtype.Numeric     `json:"rating"`
	Difficulty pgtype.Numeric     `json:"difficulty"`
	TakeAgain  pgtype.Numeric     `json:"take_again"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}
