name: Jobs Linting/Formatting

on:
  pull_request:
    paths:
      - "jobs/**"
      - ".github/workflows/jobs-styling.yml"

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Check linting
        working-directory: jobs
        run: uv run ruff check .

      - name: Check formatting
        working-directory: jobs
        run: uv run ruff format --check .